<?php echo $header; ?>
<div style="background:#ffffff;padding:10px 10px 10px 10px;border-radius:10px;margin-top:10px;margin-bottom:15px;display:inline-block;width:910px;">
<?php echo $column_left; ?>
<div class="aboutus"><br />
  <h1><?php echo $heading_title; ?></h1>
  <div id="text"><strong>Fittedhomealarms</strong> does use some non-essential cookies. We do <strong>not</strong> do this to track individual users or to identify them, but to gain useful and generic knowledge about how the site is used so that we can keep improving it for our users. Without the knowledge we gain from the systems that use these cookies we would not be able to provide the service we do.

We use Google Analytics, a popular web analytics service provided by Google, Inc. Google Analytics uses cookies to help us to analyse how users use the site. It counts the number of visitors and tells us things about their behaviour overall – such as the typical length of stay on the site or the average number of pages a user views. The information generated by the cookie about your use of our website will be transmitted to and stored by Google on servers in the United States. Google will use this information for the purpose of evaluating your use of our website, compiling reports on website activity and providing other services relating to website activity and internet usage. 

  </div>


</div>
</div>
   <?php echo $footer; ?>
